### ISSUE TITLE
Hardware requirements ?

### ISSUE THREAD

**Issue by staberas** [lingualytics/py-lingualytics#3]
What are the min hardware requirements ? Is it able to run on a Jetson nano with 2GB ram ? Thanks

**Comment by rohanrajpal** [comment]
Hey, it runs fine on a free tier colab server, so you can take that as a reference for minimum requirement.

Although, I've stopped maintaining this library long ago, so can't guarantee if it still works :(

**Comment by staberas** [comment]
Thanks, also bummer 12gb ram, apparently only NLTK is the only light weight library out there.
